name: Check

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: ["21.7"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install pdm

      - run: pdm install -v && pdm run check -v
