name: GHCR

on:
  push:
    branches:
      - main

jobs:
  ghcr:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:latest .

      - run: docker push ghcr.io/${GITHUB_REPOSITORY}:latest
